### ISSUE TITLE
Basemap not moving when dragging with the mouse

### ISSUE THREAD

**Issue by mariocasciaro** [Esri/esri-leaflet-vector#103]
I'm embedding an `esri-leaflet` in an Angularjs application. I recently upgraded to `esri-leaflet` v3 (from v2) and to using  the `vectorBasemapLayer` object for basemaps. However, when dragging the map using the mouse, the basemap wouldn't move. If there are other layers on the map, such as markers, they would move. The attribution text at the bottom of the map also gets updated correctly.
If I drag the map and then zoom, then the basemap would refresh and it would show the right location.

I tried to remove every other component or layer from the map, and left just the `setView()` and the `vectorBasemapLayer` creation, in case they were the cause of the issue, but nothing changed.

Please see the GIFs below for a visual explanation:

Basemap doesn't move:

![Screen Recording 2021-10-12 at 12 46 54](https://user-images.githubusercontent.com/105319/136951924-9bbe1c37-8d88-49ea-a6db-f8a6eacbec25.gif)

Dragging then zooming would update the basemap:

![Screen Recording 2021-10-12 at 12 43 46](https://user-images.githubusercontent.com/105319/136952177-edbe504f-4108-4851-8e6e-a1cf493863c5.gif)

I've just replaced the old `L.esri.basemapLayer` with `L.esri.Vector.vectorBasemapLayer` so there must be something in `vectorBasemapLayer` that behaves differently or has a bug. Do you have any idea of what is happening?

**Comment by gavinr** [comment]
Hi, thank you for the report. Are you able to share a replication case (using something like https://codesandbox.io for example)?

**Comment by krdyke** [comment]
Chiming in that I've encountered the same issue, although I'm using React v17.0.2 rather than Angular.

**Comment by krdyke** [comment]
also fwiw there's [an issue](https://github.com/mapbox/mapbox-gl-leaflet/issues/145) for mapbox-gl-leaflet that shows similar behavior.

**Comment by jwasilgeo** [comment]
That’s a very helpful find, thank you @krdyke!

We will look into this and consider what to potentially do about version numbers soon.

**Comment by jwasilgeo** [comment]
Fixed via https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.1.1
