### ISSUE TITLE
'load' and 'loading' events not firing on vectorBasemapLayer

### ISSUE THREAD

**Issue by mariocasciaro** [Esri/esri-leaflet-vector#104]
With `L.esri.basemapLayer` it's currently possible to get notified when all tiles are finished loading by listening to the 'load' event. Similarly, when tiles start loading, the 'loading' event is fired.
Those events are not fired when using `L.esri.Vector.vectorBasemapLayer`. Is there any plan to add those events?

**Comment by shawnmgoulet** [comment]
@mariocasciaro are we clear to close this issue after Jacob's suggestion or do we need to leave it open for further exploration? If so, could you provide additional context? Thanks!

**Comment by mariocasciaro** [comment]
Sure, we can close this for now. I will reopen it if we will encounter any issues with the mapbox-gl events.
