### ISSUE TITLE
Layer invisible since zoom level 17

### ISSUE THREAD

**Issue by javalonde** [Esri/esri-leaflet-vector#107]
Hi

I do not know if this is a bug, but the data source (VectorTiles) is displayed right to the zoom level = 17, not above, and it should be for 0-22.  Please help.

https://codepen.io/javalonde/pen/bGqpLyM

Regards,  Mik.

**Comment by jwasilgeo** [comment]
When I remove (comment out) the line that uses a legacy tiled Esri basemap (`L.esri.basemapLayer...`) I get an unconstrained `maxZoom` on the Leaflet map. Then, watching the network traffic, I see 404 errors for network requests that try to load tiles for zoom levels around 17 and above.

Are you certain this server has valid tiles for those zoom levels, despite that the service's LODs are listed as going to 24?
https://services.geodataonline.no/arcgis/rest/services/GeocacheVector/GeocacheBasisTerreng_WM/VectorTileServer

![image](https://user-images.githubusercontent.com/4933392/147601770-daf0af3d-a48b-44ed-9f69-0e9b0df905a1.png)

**Comment by javalonde** [comment]
Czesc @jwasilgeo 

I have updated possible library versions but the problem is stil there.
https://codepen.io/javalonde/pen/oNdYWMb
Here is another simple example. Vectors are not shown from zoom level 17.
When i use:
https://vector.services.geodataonline.no/arcgis/rest/services/GeocacheVector/GeocacheBasisTerreng_WM/VectorTileServer/
in arcgis-map-vierw (https://www.arcgis.com/apps/mapviewer/index.html), then,
I can observe everything much deeper.

![arcgis-viewer](https://user-images.githubusercontent.com/44463908/190108793-b6ac8417-3ae7-4026-983e-022a8e7e8a95.gif)


Regards,
Mik.

**Comment by jwasilgeo** [comment]
Czesc @javalonde. If the VectorTileServer only has tiles down to level 15, but they are visible deeper in ArcGIS Online using the ArcGIS API for JavaScript, it makes me think they are doing some resampling or "overzooming" to allow you to get closer to those same zoom level 15 tiles. I don't believe the last time I check with this plugin for Leaflet that it has this concept. What do you think @gavinr @patrickarlt?

**Comment by patrickarlt** [comment]
@jwasilgeo @javalonde By default I believe published vector tile layer layers are generated with a tile index [see the ArcGIS Pro Docs](https://pro.arcgis.com/en/pro-app/2.9/help/mapping/map-authoring/author-a-map-for-vector-tile-creation.htm#ESRI_SECTION1_9D9AA21C8EE142E9A4673F0F5219A9C8) when you use an index the client ahs to understand how to use the index to request (or overzoom and resample the tiles).

Non ArcGIS clients (like Esri Leaflet and MapLibre) don't use this index. In ArcGIS Online a special tile handler exists so that when a client requests a tile that doesn't exist the sever will user the index to generate the tile on the fly.

The solution is to republish the tiles without the index if you need compatibility with MapLibre/Esri Leaflet.

**Comment by javalonde** [comment]
@patrickarlt thanks for your commitment.
The vector source provider gave me code that shows that it works to the deepest level with MapLibre and also thinks it should work with Leaflet. What do you think?
https://codepen.io/javalonde/pen/eYrVBKo

**Comment by patrickarlt** [comment]
@javalonde I have a reproduction of this now in https://codepen.io/patrickarlt/pen/RwyvJvp?editors=0010. It does appear to work fine in MapLibre https://codepen.io/javalonde/pen/eYrVBKo?editors=1000. I'll look into why there is a difference.

**Comment by javalonde** [comment]
@patrickarlt It looks at in MapLibre there are no more request for new data when zoom is higher than 15.  Perhaps it's using already collected vector data.

**Comment by patrickarlt** [comment]
@gavinr @javalonde I tracked down this down to https://github.com/Esri/esri-leaflet-vector/blob/master/src/Util.js#L150-L154. We are setting the min and max zoom to the LODs that are published with the service.

You can see a solution in https://codepen.io/patrickarlt/pen/XWYoBKE?editors=0010 were we manually set the proper max zoom.

It looks like we may need to look at `minLOD`/`maxLOD` properties but it isn't listed in the docs https://developers.arcgis.com/rest/services-reference/enterprise/vector-tile-service.htm so I'm not 100% sure we can rely on it. I'll follow up internally and see what if any property we can rely on.
