### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by smartcmsteam** [Esri/esri-leaflet-vector#113]
### Describe the problem

Hello,

I don't see any where to change the language in the map. How can I set it to German?

Thanks

### Describe the proposed solution

Add a parameter to URL

**Comment by gavinr** [comment]
Hi, thanks for the question. We're assuming you're asking about seeing German for the basemap labels.

1. Find the group for your language from [this blog post](https://www.esri.com/arcgis-blog/products/arcgis-online/announcements/whats-new-in-esri-vector-basemaps-may-2019/). (For German, the group is [here](https://www.arcgis.com/home/group.html?id=00c428a3eb7448f8ade9791f017f0fff#overview))
3. Browse through the list of basemap styles in that group and find the one you want and click it.
4. On the item page for the web map, you can see the multiple layers that are included in that basemap. For each, get the itemID by clicking on it and copy/pasting the ID from the URL.
    ![image](https://user-images.githubusercontent.com/209355/151380916-df99a014-9f71-42ec-8adb-15983397ba1f.png)
5. Use that itemId with `L.esri.Vector.vectorTileLayer` like this:
    ```js
    L.esri.Vector.vectorTileLayer("b30fcf697a02466f87c2df67bd76b481").addTo(map);
    ```

Here is a full example: https://codepen.io/gavinr/pen/MWOYGOB?editors=0010

**Comment by smartcmsteam** [comment]
thank you, it works!
