### ISSUE TITLE
get vector.Layer working with tiles published from ArcGIS Pro

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-vector#12]
@cegoddard can i ask you to:
1. publish a vector tile service with a single layer
2. make it public
3. share the url

please? 🍰

**Comment by cegoddard** [comment]
http://tiles.arcgis.com/tiles/f2L9BNb7FaGJkvSP/arcgis/rest/services/vtpk_cities/VectorTileServer

**Comment by jgravois** [comment]
thanks!  can you share the ArcGIS Online item id for this new service as well?

https://www.arcgis.com > My Content > Vector Tile Service > thing at the end of the url

**Comment by jgravois** [comment]
working mapbox-gl-js example:
http://jsbin.com/fepobey/edit?html,output

the same sample stops drawing features in [`0.23.0`](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.23.0). are we affected by the breaking  `LngLatBounds` change?

**Comment by cegoddard** [comment]
vtpk_cities id=0bac0ffdc8634d9a9bc662bb8fa7547d

Resources for LngLatBounds
https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.23.0

https://github.com/mapbox/mapbox-gl-js/pull/2414

https://github.com/mapbox/mapbox-gl-js/issues/2415

**Comment by cegoddard** [comment]
John, had you heard of [MapProxy ](https://mapproxy.org/)before?

**Comment by jgravois** [comment]
> have you heard of MapProxy before?

I haven't.
