### ISSUE TITLE
Angular or another SPA example for Codesandbox or Stackblitz

### ISSUE THREAD

**Issue by Celtian** [Esri/esri-leaflet-vector#128]
Hello,

can you please add into readme some examples for SPA (Angular, React, ...) application in Codesandbox or Stackblitz (or both). In my opinion, it should be part of readme of all npm libs where is it possible. Example + text coverage badge is for me sign of quallity of package.

**Comment by gavinr** [comment]
Hi, Esri Leaflet Vector is not framework-specific, so there's nothing unique you need to do to run it using a particular framework. 

- Here is a React demo: https://github.com/gavinr/esri-leaflet-react-demo
- Here is a svelte demo: https://github.com/gavinr/esri-leaflet-svelte-demo
- Here is a React wrapper that may help you out: https://github.com/slutske22/react-esri-leaflet
- Here are tutorials: on how to get started: https://developers.arcgis.com/esri-leaflet/tutorials/

I hope this helps!
