### ISSUE TITLE
Compatibility with leaflet.markercluster

### ISSUE THREAD

**Issue by Celtian** [Esri/esri-leaflet-vector#131]
Hello,

Your library is not obviously compatible with 

https://www.npmjs.com/package/leaflet.markercluster

It is caused by "Map has no maxZoom specified" (probaly "maxNativeZoom" need to be renamed "maxZoom ") ...

Can you fix it or publish related example?

**Comment by gavinr** [comment]
Hi, have you tried https://github.com/Esri/esri-leaflet-cluster?

**Comment by Celtian** [comment]
Does it work also with another sources? Not just esri ...

**Comment by gavinr** [comment]
Oh, I think I'm now understanding you: Are you saying that when using the `esri-leaflet-vector` layer AND `leaflet.markercluster` on the same leaflet map, you get an error?

**Comment by Celtian** [comment]
We are using also layers from different prividers like `mapy.cz` or `here.maps` or `mapbox` or ... is it compatible or it is onlz working with leaflet. For us is useless to use clustering only for esri layers but not for anothe ones ...

**Comment by gavinr** [comment]
Sorry, I'm a bit confused by your question. And I don't think you answered my question: Are you saying that when using the `esri-leaflet-vector` layer AND `leaflet.markercluster` on the same leaflet map, you get an error?

If you are seeing a specific issues with `esri-leaflet-vector`, please post a replication case showing the issue.

**Comment by gavinr** [comment]
Ok, can you please post a public replication case (perhaps using a service like CodePen or JSBin) that shows the issue?

**Comment by shawnmgoulet** [comment]
@Celtian - want to reach back out again on this. We need a replication case to work from, otherwise, we will need to close this issue as we will not be able to work on it without one. Thanks!

**Comment by arschmitz** [comment]
I can confirm i have successfully been using these together in a large scale production app for quite some time without issue it just needs to be configured correctly
