### ISSUE TITLE
Vector tile layer attribution issues

### ISSUE THREAD

**Issue by ItaiEinhorn** [Esri/esri-leaflet-vector#142]
### Describe the bug

1. The same issue with the missing 'Powered by Esri' attribution is occurring in VectorTileLayers
This issue: https://github.com/Esri/esri-leaflet-vector/issues/133
Was fixed here: https://github.com/Esri/esri-leaflet-vector/pull/135
This was fixed on the VectorBasemapLayer entity, i believe the same code should be applied to VectorTileLayer entity as well
see this codepen example: https://codepen.io/ItaiE/pen/dymgzLE (Esri Leaflet Vector basemap - via item ID - doesn't have 'Powered by Esri' attribution)

2. The reason i didn't use the VectorBasemapLayer entity is because i found another issue:
When removing the VectorBasemapLayer from the map, the attribution doesn't get cleared and so when loading a new layer, the old attribution remains.
See the codepen for reference:  https://codepen.io/ItaiE/pen/KKoGvqg
Clicking on the 'Remove Layer' button will remove the VectorBasemapLayer but not it's attribution

### Reproduction

https://codepen.io/ItaiE/pen/dymgzLE

https://codepen.io/ItaiE/pen/KKoGvqg

### System Info

```shell
Latest
```

**Comment by gavinr** [comment]
Thank you for the report.

For your issue 1, I think you're correct - we should make that change. 
For your issue 2, I think that's already covered here: #136, correct?

Thanks!

**Comment by ItaiEinhorn** [comment]
1. Thank you
2. Indeed, 136 seems to cover it

**Comment by gavinr** [comment]
Ok, closing this in favor of #143. Thank you!
