### ISSUE TITLE
Change VectorBasemapLayer to inherit from VectorTileLayer

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-vector#150]
### Describe the problem

There is some duplication of code between [VectorBasemapLayer](https://github.com/Esri/esri-leaflet-vector/blob/master/src/VectorBasemapLayer.js) and [VectorTileLayer](https://github.com/Esri/esri-leaflet-vector/blob/master/src/VectorTileLayer.js).

### Describe the proposed solution

Should we change VectorBasemapLayer to inherit from VectorTileLayer? We should investigate if that's possible and if it would provide benefits.

### Additional Information

@patrickarlt may have additional context that I forgot to include here.

**Comment by patrickarlt** [comment]
I don't have anything to add here but I think this would be a good change.

**Comment by gavinr** [comment]
Complete in [v4.1.0](https://github.com/Esri/esri-leaflet-vector/releases/tag/v4.1.0).
