### ISSUE TITLE
Still getting error "Error: missing required property "version" "sources" and "layers""

### ISSUE THREAD

**Issue by Rayvenhaus** [Esri/esri-leaflet-vector#155]
### Describe the bug

I have followed the direction at https://developers.arcgis.com/esri-leaflet/geocode-and-search/search-for-an-address/ to implement address geocoding on my website at https://wendydev.myndworx.com.au:4443/settingsTest/testing.php . The map is created, though no tiles are shown. However, the search control is created and works as shown in the attached images. The following errors are generated on page load:
missing required property "version"
missing required property "sources"
missing required property "layers"

This same error was called out in Issue #76, now closed and mentioned in #28 and #80, both of which are also now closed.

![2022-12-28 10_44_01-](https://user-images.githubusercontent.com/4164076/209737139-a904a7db-b927-4cb8-a4ce-e09dc15e9f5a.png)

### Reproduction

Load web page

### System Info

```shell
Leaflet v: 1.9.3
esri-Leaflet v: 3.0.9
esri-leaflet-vector v: 4.0.0
esri-leaflet-geocoder v: 3.1.3
```

**Comment by gavinr** [comment]
Hi, thanks for the question. I cannot load that page - can you please post a public jsfiddle or codepen that demonstrates the issue?

**Comment by Rayvenhaus** [comment]
https://jsfiddle.net/Rayvenhaus/h7yx9w0g/

**Comment by gavinr** [comment]
Thanks for the code. It seems like there's an issue with Jsfiddle, but if you copy/paste your jsfiddle code into JSbin, it works fine:
![image](https://user-images.githubusercontent.com/209355/209975063-3dc765bd-8183-4ec8-94d9-a0ace000d82d.png)

https://jsbin.com/qonuyoz/edit?html,output

**Comment by Rayvenhaus** [comment]
With that, I was able to track it down. It was browser related, on my end. Thanks for the assist, mate.
