### ISSUE TITLE
Weird offset / distortion a high zoom level

### ISSUE THREAD

**Issue by sweco-nlmdek** [Esri/esri-leaflet-vector#164]
### Describe the bug

Tiles rendered incorrect when zooming in to much :
![image](https://user-images.githubusercontent.com/87322335/225108018-8a30e85c-ef35-4ca4-a614-2b90d1f036c3.png)

### Reproduction

Sorry, no reproduction made yet

### System Info

```shell
"leaflet": "^1.9.3", "react-esri-leaflet": "^2.0.1","esri-leaflet-vector": "^4.0.1",
```

**Comment by gavinr** [comment]
Thanks for reporting this. Please post a replication case so we can help work through the issue.
