### ISSUE TITLE
Can't resolve 'maplibre-gl' in version 4.0.2

### ISSUE THREAD

**Issue by XardasLord** [Esri/esri-leaflet-vector#168]
### Describe the bug

After upgrading to 4.0.2 I'm getting the following error after running my app:
```
./node_modules/esri-leaflet-vector/dist/esri-leaflet-vector-debug.js:5:127-149 - Error: Module not found: Error: Can't resolve 'maplibre-gl' in 'C:\localRepositories\Private\EOP.GeoLink\src\GeoLink.Client\node_modules\esri-leaflet-vector\dist'
```

### Reproduction

- Upgrade esri-leaflet-vector package to 4.0.2
- Run app

### System Info

```shell
Leaflet - v1.9.3
esri-leaflet - v3.0.10
esri-leaflet-renderers - v3.0.0
esri-leaflet-vector - v4.0.2"
```

**Comment by gavinr** [comment]
Hi, thank you for the report. v4.0.2 is working here:
https://jsbin.com/humavuhuve/2/edit?html,output

and it looks like you're using it in NPM, so I tested it here: https://github.com/gavinr/esri-leaflet-react-demo and v4.0.2 seems to work there too.

So can you please share a detailed, step by step replication case so I can fully understand the issue you're running into? Thank you!
