### ISSUE TITLE
Add support for the basemap styles service v2 (beta)

### ISSUE THREAD

**Issue by gowin20** [Esri/esri-leaflet-vector#174]
### Describe the problem

Esri leaflet does not currently support Esri's [new basemap styles service v2](https://developers.arcgis.com/rest/basemap-styles/)

### Describe the proposed solution

Add a new class in order to access the v2 service.

**Comment by gavinr** [comment]
Complete in [v4.1.0](https://github.com/Esri/esri-leaflet-vector/releases/tag/v4.1.0).
