### ISSUE TITLE
Add support for a proxy

### ISSUE THREAD

**Issue by pdiddyb** [Esri/esri-leaflet-vector#190]
### Describe the problem

I do not see a parameter to add a proxy to proxy when adding a L.esri.Vector.vectorTileLayer.  I can add the proxy to the portalUrl, but after the initial calls it will start making requests for tiles to the server address from the service.

### Describe the proposed solution

If we had a proxy parameter then we would be set that.
Currently I am trying this by prepending the proxy to the portalUrl:

```
      var l1 = L.esri.Vector.vectorTileLayer(itemID, {
        portalUrl: proxyUrl + '?' + portalURL,
      });

```
If we had a proxy parameter then it would look like this:
```
      var l1 = L.esri.Vector.vectorTileLayer(itemID, {
        portalUrl: portalURL,
        proxy: proxyUrl,
      });
```

**Comment by pdiddyb** [comment]
@gavinr-maps We went ahead and added a proxy property.  I made [PR 193](https://github.com/Esri/esri-leaflet-vector/pull/193)

**Comment by gavinr-maps** [comment]
@pdiddyb thank you for the PR. The  reason I asked for the replication case was that I wanted to see if doing what you want is possible already using the `style` property function. In theory you can use the style function to manually change the URLs to point to a proxy. Are you able to give that a try?

**Comment by patrickarlt** [comment]
@pdiddyb I would recommend using the `style` option io transform the style after it retrieved from teh portal:

```js
      var l1 = L.esri.Vector.vectorTileLayer(itemID, {
        portalUrl: proxyUrl + '?' + portalURL,
        style: (portalStyle) => {
          // modify URLs in the portal style to point to your proxy.
          return portalStyle
        }
      });
```

Testing and implementation of a `proxy` parameter opens up quite a bit of maintenance surface area. Additionally documenting exactly what and which proxy to use and what the proxy supports will be difficult and add additional surface area and support to the API.
