### ISSUE TITLE
Update to maplibre-gl v3

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-vector#194]
### Describe the problem

v3 of maplibre-gl was [released in May](https://github.com/maplibre/maplibre-gl-js/releases). Since we package maplibre-gl with this library, it probably makes sense to test if upgrading will work,

### Describe the proposed solution

If upgrading will work, we can go ahead and update the dependency: 
https://github.com/Esri/esri-leaflet-vector/blob/bbc8d12707c40530cc68469d2f258e2f2e2dfa4e/package.json#L17

Will this require a major semver version increase afterward (v4 to v5)? I don't think so since none of our library APIs should change, but open for discussion if I'm missing anything.

**Comment by sheeley820** [comment]
As side note in regards to `maplibre-gl`, is there a specific reason `MaplibreGLJSLayer` is not exported in `EsriLeafletVector.js`?  In particular when working with printing plugins for Leaflet I ran into an issue where the Maplibre layer needed to be associated with a layer type, but that type is not exposed by the project.  Would it be possible to just add `export { MaplibreGLJSLayer, maplibreGLJSLayer } from './MaplibreGLLayer';`?

**Comment by sdthaker** [comment]
Hi @gavinr @gavinr-maps, Could you please assign this issue to me? I'd like to contribute to this issue as part of Hacktoberfest.

**Comment by gavinr-maps** [comment]
Hi @sdthaker, thanks for taking a look. No need to wait for us to assign it - just go ahead and work on it and submit a PR! (in fact usually we do not assign issues on our open source repos)

**Comment by sdthaker** [comment]
Is there a specific minor version that needs to be installed for maplibre-gl or the latest v3 should do, which happens to be v3.3.1? @gavinr-maps

**Comment by gavinr-maps** [comment]
Current latest should be fine. Thanks!
