### ISSUE TITLE
Custom vector tile service not displaying.

### ISSUE THREAD

**Issue by shadc** [Esri/esri-leaflet-vector#20]
Using CDN... 
 <script src="https://unpkg.com/esri-leaflet-vector@1.0.5"></script>

vector tile service:
L.esri.Vector.layer('c09b3bdbf3f741128e13a1817052e32c').addTo(map);

**Comment by jgravois** [comment]
i just patched the bug and released `1.0.6`. can you confirm whether it resolves the problem on your end?

**Comment by shadc** [comment]
Fixed... thanks!!
