### ISSUE TITLE
Add support for new v2 basemap parameters

### ISSUE THREAD

**Issue by gowin20** [Esri/esri-leaflet-vector#213]
### Describe the problem

Esri has released support for the following parameters in the v2 basemap styles service:

`places`: set to `all` or `attributed` to view POI displayed on the basemap
`worldview`: set to a supported string to view the world map endorsed by that country or group

### Describe the proposed solution

We need to add support for both parameters into the `vectorBasemapLayer` function. Their implementation should be identical to the newly added `language` parameter.

**Comment by gavinr-maps** [comment]
This was added in [v4.2.3](https://github.com/Esri/esri-leaflet-vector/releases/tag/v4.2.3).
