### ISSUE TITLE
Licence file is missing, needs reinstated

### ISSUE THREAD

**Issue by martingraham** [Esri/esri-leaflet-vector#225]
### Describe the problem

The local licence referenced in the readme is not present -->
https://github.com/Esri/esri-leaflet-vector/blob/master/LICENSE

I know the readme says which licence it uses, but its easier to persuade people we can use this library if I can point straight to a licence file

Must have been present at some point to be linked?

### Describe the proposed solution

Add the licence file back in

**Comment by gavinr-maps** [comment]
Hi, thank you for logging this issue. You're correct that it is mentioned in the README but there is no license file itself. PRs are welcome to add it!

**Comment by A-4-Atom** [comment]
Hi, I'd like to work on it. Can you assign this issue to me? 
@gavinr-maps

**Comment by patrickarlt** [comment]
@A-4-Atom assigned to you. I can review a PR when your ready.

**Comment by Kizito007** [comment]
This still hasn't been added. Can I proceed on doing so?

Cc @patrickarlt

**Comment by gavinr-maps** [comment]
@Kizito007 sure, PRs are welcome.
