### ISSUE TITLE
alternate styles for ArcGIS Pro published vector tilesets are not honored

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-vector#29]
ref: https://github.com/Esri/esri-leaflet/issues/943

> Leaflet v.1.0.3
esri Leaflet v.2.0.8 (master)

> Steps to reproduce the error:

> When adding an ArcGIS Online Item for an alternate style created for an ArcGIS Vector Tile layer to the map, the root.json file of the basic style attached to the tile service is used, instead of alternate styles attached to the ArcGIS Online/Portal item.

> The built-in basemap Vector Tiles added using L.esri.Vector.basemap properly fetch their alternate root.json files from "https://www.arcgis.com/sharing/rest/content/items/" + AGOL ID + "/resources/styles/root.json", while layers added using L.esri.Vector.layer will default to the default style of the cache referenced by the alternate style (Typically something like http://tiles.arcgis.com/tiles/XXX/arcgis/rest/services/XXX/VectorTileServer/resources/styles/root.json

> Hopefully this is enough info; I can structure a working example if required.

**Comment by jgravois** [comment]
sorry for the delay, but i finally got a chance to look into this and i'm not able to reproduce the error that has been described.

http://jsbin.com/zivoto/1/edit?html,output

```js
var map = L.map('map').setView([40, -4], 6);

/* 
http://www.arcgis.com/home/item.html?id=bd505ce3efff479bb4e87b182f180159
the item above references a custom light green color scheme to Esri's hosted gray vector tile basemap
*/
L.esri.Vector.layer('bd505ce3efff479bb4e87b182f180159').addTo(map);
```
@cmndrbensisko can you provide more information and/or a repro case please?
maybe its specific to alternate styles for vector tilesets published using ArcGIS Pro?

**Comment by jag-eagle-technology** [comment]
This is an issue - your test above references Esri's hosted gray vector tile basemap rather than one you have published.
