### ISSUE TITLE
Road shields not displaying

### ISSUE THREAD

**Issue by ecmanghi** [Esri/esri-leaflet-vector#33]
I noticed road shields do not display in both vector layers and basemaps.  Could an image link be broken?

esri-leaflet-vector
![image](https://user-images.githubusercontent.com/15742079/29419494-437607b8-833d-11e7-8e78-81a7097b080e.png)

Esri JS API
![image](https://user-images.githubusercontent.com/15742079/29419589-7adc91e0-833d-11e7-8df1-210733a46c48.png)

**Comment by ecmanghi** [comment]
Correction: I think this is an issue on my end of things.  You can close it.

**Comment by jgravois** [comment]
> in both vector layers and basemaps

i'm not seeing this in our live sample when zooming into LA

**Comment by ecmanghi** [comment]
Hi John,
Thanks for your quick response think this is an issue on my end but I’m not sure what’s causing it.  You can close it.  Thanks,
Beth

**Comment by jgravois** [comment]
no worries! its hidden in the bottom left corner, but you should be able to do it yourself too.
