### ISSUE TITLE
L.esri.Vector.layer issue

### ISSUE THREAD

**Issue by blahmonkey** [Esri/esri-leaflet-vector#34]
Hi,

Trying to do 

`L.esri.Vector.layer('2f030643ec154495b25256784f5e7d24').addTo(this.mapView)`

I get these console errors (network issues) below, and the tile layer does not display, with or without a basemap layer (basemap layer loads fine e.g newspaper.

```
http://www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/sprites/sprite@2x.json 403 (Forbidden)
http://www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/sprites/sprite@2x.png 403 (Forbidden)
http://www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/fonts/Arial%20Regular/0-255.pbf 403 (Forbidden)
http://www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/fonts/Palatino%20Linotype%20Regular/0-255.pbf 403 (Forbidden)
http://www.arcgis.com/sharing/rest/content/items/be44936bcdd24db588a1ae5076e36f34/resources/fonts/Arial%20Italic/0-255.pbf 403 (Forbidden)
```

The item is publicly shared, and I also tried with token (testing token). 

**Update** 
The tile layer is loading now, but some issues - the 403s above are still happening. And unless I use zoom level 1 for L.map(), the visible area shows up as grey, and the tiles show up only when I zoom out. Plus, when I pan the map I end up with weird issues with my markers (sometimes only the tiles move, not the markers)

Sample code
```
<html>
<head>
  <meta charset=utf-8 />
  <title>Esri Vector Basemap</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

  <!-- Load libraries from CDN -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.0.3"></script>

  <!-- Esri Leaflet and Esri Leaflet Vector -->
  <script src="https://unpkg.com/esri-leaflet@2.0.8"></script>
  <script src="https://unpkg.com/esri-leaflet-vector@1.0.7"></script>

  <style>
    body {margin:0;padding:0;}
    #map {position: absolute;top:0;bottom:0;right:0;left:0;}
  </style>
</head>
<body>

<div id="map"></div>

<script>
  var map = L.map('map').setView([59.358353, 17.907425], 14);
  L.esri.Vector.layer('2f030643ec154495b25256784f5e7d24').addTo(map);
  // L.esri.Vector.basemap('Newspaper').addTo(map);
</script>

</body>
</html>
```

**Comment by blahmonkey** [comment]
Further note - I tried with the below 'storymap' custom layer I found by browsing the issues board here (got this url http://storymaps.esri.com/stories/2016/vector-basemaps/ ), and this works fine - no 403s, and the map loads fine as well, no need to zoom out to see the tiles

` L.esri.Vector.layer('cc82d6c506cc4accadea6cc377ed1fe0').addTo(map);`

**Comment by blahmonkey** [comment]
@jgravois Any idea what might be wrong? Definitely in the internals...I will try to take a look but would appreciate it if you could check it out

**Comment by jgravois** [comment]
i can't repro the error with a layer i just created using our [Application Prototype Lab](https://maps.esri.com/jg/VectorBasemapStyleEditor/index.html) editor.

http://jsbin.com/hohoyey/edit?html,output
https://www.arcgis.com/home/item.html?id=6c34522d1cb64af5ad1bd1b281d44668

how did you create your layer? when?

**Comment by blahmonkey** [comment]
Interesting.

Our goal was to custom-style a vector basemap (in this case 'topographical') to apply a custom style we'd use with Google Maps (happy to move away from it)

I used this blog as a guide around 10-12 days ago to accomplish this --
https://blogs.esri.com/esri/arcgis/2015/11/19/how-to-customize-esri-vector-basemaps/

It worked perfectly fine, we were able to have a layer whose root.json we downloaded, modified, uploaded, could see the (random red color) easily on the map. We were also able to see this style in your 'Style editor' -- http://esri.github.io/arcgis-vectortile-style-editor/#

I can see on logging in to your APL editor ( https://maps.esri.com/jg/VectorBasemapStyleEditor/index.html ) that our item is there as well.

Do you think it would work better if we began from the APL editor, imported a basemap, and then tried to style?

Thanks for your time!

**Comment by blahmonkey** [comment]
Update -- tried with your jsbin, forked it, modified the item id, and tried with/without token.

Network inspector shows this error
<img width="1433" alt="screen shot 2017-09-20 at 1 02 16 pm" src="https://user-images.githubusercontent.com/3027923/30631968-f3366658-9e03-11e7-8d4b-c94b053a7b57.png">

The item is shared with public. The account is an enterprise account @ arcgis.com. Token I tried is from a developer account (same credentials), not sure how to get a token from the enterprise account directly

Any idea what might be going wrong?

**Comment by jgravois** [comment]
> The item is shared with public. ... Token I tried is from a developer account

When you share an item publicly any app *should* be able to access the content without supplying a token.

> Do you think it would work better if we began from the APL editor?

the issue isn't so much the particular editor as it is what specific tile layer you copy/paste and start modifying. the difference between yours that fails and mine is the underlying service.  

mine
http://www.arcgis.com/home/item.html?id=c50de463235e4161b206d000587af18b
>Layers > World Basemap > https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer

yours
http://www.arcgis.com/home/item.html?id=2f030643ec154495b25256784f5e7d24
> Layers > World Basemap > http://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer
(notice the lack of a `v1` in the url)

if you modify a copy of an item that references a `v1` VectorTileServer, i'd expect it to display in esri-leaflet-vector.

i _think_ the root of the confusion is that the blog from 2016 still directs users to search for `owner:esri_vector` content but the most recent generation of vector basemaps are owned by plain old 'esri'

examples:
[Navigation](http://www.arcgis.com/home/item.html?id=e19e9330bf08490ca8353d76b5e2e658)
[World Topographic Map](http://www.arcgis.com/home/item.html?id=86d5ed4b6dc741de9dad5f0fbe09ae95)

**Comment by blahmonkey** [comment]
Perfect, got it working!

For anybody else who reads this - I created an item with v1 in the URL by using the APL ( https://maps.esri.com/jg/VectorBasemapStyleEditor/index.html ) and choosing 'copy esri basemap item'. This item I then shared publicly after styling and saving it in the APL. I then visited my arcgis.com account, to get the item-id from the URL of the item (from the 'content' section)

Now this is loading fine in the jsbin! Thank you very much for your help.

I have a small side question -- I know developer accounts have 1M map transactions/month limits. When we use a basemap layer like in this case without a token, what are the limits which apply?

(I apologize if this is not the appropirate place to ask, please point me to the right place if so)

**Comment by jgravois** [comment]
glad to hear it.

> When we use a basemap layer like in this case without a token, what are the limits which apply?

the same limits apply whether the basemap you load is private or public.

**Comment by blahmonkey** [comment]
Great answers, thanks :)
