### ISSUE TITLE
Map glitches (Custom map)

### ISSUE THREAD

**Issue by blahmonkey** [Esri/esri-leaflet-vector#37]
Hi,

Facing issues with a custom map (styled it using your style editor). 

Tested on Chrome, Firefox on Windows 10 + OSX Sierra. The pic below is from Chrome + Win10

The issues include:
1. Much slower loading of tiles than the raster basemaps
2. Glitches like the one in the picture -- you can see a transparent 'lithuania' east of belgium, 'denmark' to its left (not seen in raster basemaps)
3. Occasional tile corruption (not seen in raster basemaps) - where when you zoom in/out, some tiles are of the original zoom level, and some of the final zoom level

Any idea what the issue could be? Feels like Pt 2 + 3 are the same issue...

Item id is 9ab879103c6d4fb8a63b39429fa1c4a9

Code I'm using is
`L.esri.Vector.layer('9ab879103c6d4fb8a63b39429fa1c4a9').addTo(map)`

[glitch-map](https://user-images.githubusercontent.com/3027923/31659882-3034928c-b353-11e7-9cde-61e8dfd4777c.jpeg)

**Comment by blahmonkey** [comment]
FYI -- I tried with render: L.canvas() as well -- get the same issues as above.

@jgravois Any ideas?

**Comment by jgravois** [comment]
sorry for the extermely delay reply. i pushed some updates and tested against `master` and drawing behavior with your layer seemed solid.

happy to reopen if you are still experiencing issues with the latest.
