### ISSUE TITLE
Using v2 Basemaps causes points to draw in wrong hemisphere

### ISSUE THREAD

**Issue by cloydc** [Esri/esri-leaflet-vector#44]
I'd like to update our web maps to use the v2 vector basemaps. When I attempt to plugin the ID's for the v2 maps, the feature layers draw in the wrong location. It appears they are drawing on the southern hemisphere of the map, instead of the northern hemisphere. 

Existing map using the old Newspaper basemap.
Code: var map_layer = new L.esri.Vector.basemap('Newspaper');

<img width="782" alt="screen shot 2018-03-27 at 4 21 06 pm" src="https://user-images.githubusercontent.com/1933853/37995678-e401ab78-31da-11e8-9a06-253efadcca4d.png">

Now using a v2 basemap
Code: var map_layer = new L.esri.Vector.layer('41597245552743d5910de614d47e748c');

<img width="788" alt="screen shot 2018-03-27 at 4 20 33 pm" src="https://user-images.githubusercontent.com/1933853/37995724-01789bda-31db-11e8-8b5e-33d0ce48b427.png">

I tried adding the v2 map to the styles in the esri-leaflet.js file and got the same results. Any ideas on how to remedy this? I'm new to using ESRI Leaflet so any suggestions appreciated.

**Comment by jgravois** [comment]
i currently can't even build the source for this plugin locally (described in https://github.com/Esri/esri-leaflet-vector/issues/22#issuecomment-366008229) so its unlikely you'll see additional fixes for this lib anytime soon.

if you're interested in vector basemaps you're much better off using version [4.x](https://developers.arcgis.com/javascript/latest/sample-code/layers-vectortilelayer/index.html) of the ArcGIS API for JavaScript (and [esri loader](https://github.com/Esri/esri-loader) if you're using another _opinionated_ framework).

**Comment by jgravois** [comment]
ugh, i figured out your problem. the item you referenced is a [WGS84](https://www.arcgis.com/home/item.html?id=41597245552743d5910de614d47e748c) tiled basemap.

you could try supplying a custom CRS when you instantiate your leaflet map, but it'd be much easier to just use the [web mercator](https://www.arcgis.com/home/item.html?id=de26a3cf4cc9451298ea173c4b324736) version instead.

```js
L.esri.Vector.layer('de26a3cf4cc9451298ea173c4b324736');
```
