### ISSUE TITLE
StreetsNight

### ISSUE THREAD

**Issue by DucHo7** [Esri/esri-leaflet-vector#46]
When to fixed StreetsNight basemap

**Comment by jgravois** [comment]
thanks for the report.

it looks to me like we're choking on a bad hexidecimal color in the style.json for the layer.

[`#3a6a664`](https://www.arcgis.com/sharing/rest/content/items/92c551c9f07b4147846aae273e822714/resources/styles/root.json?f=json)

i've passed along the report to the same that maintains the [service](http://www.arcgis.com/home/item.html?id=92c551c9f07b4147846aae273e822714) but it has been deprecated, so no guarantees.

**Comment by jgravois** [comment]
the typo in the `v1` World Street (Night) basemap has been fixed, which resolved the problem in this plugin. 

thanks again for your report.
