### ISSUE TITLE
ESRI Vector tile not found

### ISSUE THREAD

**Issue by pluservice** [Esri/esri-leaflet-vector#53]
At zoom level >12 

get https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/12/1495/2202.pbf
{"error":{"code":404,"message":"The requested URL was not found.","details":[]}}

https://codepen.io/anpasq/pen/WWBQYP

![image](https://user-images.githubusercontent.com/17173722/56954600-77e32f80-6b3f-11e9-9096-ce6cf6a46189.png)

**Comment by jgravois** [comment]
this is a particularly bad example of the third disclaimer in the README.

> 404s will be encountered when zooming in past zoom level 15 in areas without much feature density.

one option you might consider is reverting to `v1.x`, where we still bundled `mapbox-gl-js` internally, and we used a stale fork that included Esri's indexed implementation that resamples missing tiles.

**Comment by pluservice** [comment]
By the way in this case the problem occurs with a zoom level of 13.
With this limitations, unfortunately  the plugin is unusable.

**Comment by jwasilgeo** [comment]
Hi @pluservice, we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet and esri-leaflet-vector v3. I'll close this with the hope that it won't be an issue anymore with the latest library versions, but do let us know if there are still problems for you.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
