### ISSUE TITLE
L.esri.Vector.Layer calls URL twice

### ISSUE THREAD

**Issue by Mak-NOAA** [Esri/esri-leaflet-vector#59]
## Describe the bug

I'm using https://esri.github.io/esri-leaflet/api-reference/layers/vector-layer.html to call a NOAA.gov vector tile map but the map is not loading. It's also calling the URL twice. First it calls the URL direct and gets a response, the 2nd time it calls it with "https://www.arcgis.com/sharing/rest/content/items/" prefixed to the URL

## Expected behavior

Call the URL once and don't prefix "https://www.arcgis.com/sharing/rest/content/items/"
In my code, I'm calling the vector tile as such    

```
 node.data.layer = 
L.esri.Vector.layer('https://.....NOAA.GOV/server/rest/services/Hosted/Acoustics_Survey2012/VectorTileServer');

                                        node.data.layer = L.esri.Vector.layer('https://[IP address here]/server/rest/services/Hosted/Acoustics_Survey2012/VectorTileServer');


                                map.addLayer(node.data.layer);
```

## Actual behavior

Calls to the URL

## To Reproduce

Please share the steps to reproduce the behavior.

## Environment Information

<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
  | <script src="https://cdn.jsdelivr.net/npm/leaflet-measure@3.0.3/dist/leaflet-measure.min.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/esri-leaflet/2.1.2/esri-leaflet.js"></script>
  | <script src="https://unpkg.com/esri-leaflet-vector@2.0.2/dist/esri-leaflet-vector.js"
  | integrity="sha512-keaVwrBxpBNq1XF5XEUvQ8NtoBbGPs/gKJJ3tp1qiudO3mTk9YEa6/uPpxX/G2HIjFrquj/xGg+p/c7nDp0wUg=="
  | crossorigin=""></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.3.0/leaflet.markercluster-src.js"></script>
  | <script src="vendor/leaflet/leaflet.extra-markers.min.js"></script>
  | <script src="https://unpkg.com/leaflet-easybutton@2.0.0/src/easy-button.js"></script>
 

Chrome
Macbook

**Comment by jgravois** [comment]
> First it calls the URL direct and gets a response

can you copy/paste that JSON?

**Comment by Mak-NOAA** [comment]
@jgravois thanks for transferring this issue to https://github.com/esri/esri-leaflet-vector

Below is the request and response from the two calls:

Request URL:
https://[I have the IP address here]/server/rest/services/Hosted/Acoustics_Survey2012/VectorTileServer?f=json
w/ response:

`{"name":"Layers","copyrightText":"NOAA Fisheries, Northwest Fisheries Science Center, Fishery Resource Analysis and Monitoring Division","type":"indexedVector","tileMap":"tilemap","defaultStyles":"resources/styles","tiles":["tile/{z}/{y}/{x}.pbf"],"initialExtent":{"xmin":-14960220.3081,"ymin":4272564.220800000243,"xmax":-13513333.1074,"ymax":7349601.2511,"spatialReference":{"wkid":102100,"latestWkid":3857}},"fullExtent":{"xmin":-14960220.3081,"ymin":4272564.220800000243,"xmax":-13513333.1074,"ymax":7349601.2511,"spatialReference":{"wkid":102100,"latestWkid":3857}},"minScale":295828763.7957775,"maxScale":35.26553675000000254,"tileInfo":{"rows":512,"cols":512,"dpi":96,"format":"pbf","origin":{"x":-20037508.34278700128,"y":20037508.34278700128},"spatialReference":{"wkid":102100,"latestWkid":3857},"lods":[{"level":0,"resolution":78271.51696399999491,"scale":295828763.7957775},{"level":1,"resolution":39135.75848199994653,"scale":147914381.8978885114},{"level":2,"resolution":19567.87924100005,"scale":73957190.94894449413},{"level":3,"resolution":9783.939620499950252,"scale":36978595.47447200119},{"level":4,"resolution":4891.969810249979673,"scale":18489297.7372360006},{"level":5,"resolution":2445.984905124989837,"scale":9244648.8686180003},{"level":6,"resolution":1222.992452562494918,"scale":4622324.434309000149},{"level":7,"resolution":611.496226281244958,"scale":2311162.217154500075},{"level":8,"resolution":305.748113140690009,"scale":1155581.1085775001},{"level":9,"resolution":152.8740565702790093,"scale":577790.5542884999886},{"level":10,"resolution":76.4370282852055,"scale":288895.2771445},{"level":11,"resolution":38.2185141425365984,"scale":144447.638572},{"level":12,"resolution":19.1092570712682992,"scale":72223.8192859999981},{"level":13,"resolution":9.5546285356341496,"scale":36111.90964299999905},{"level":14,"resolution":4.7773142678170748,"scale":18055.9548215},{"level":15,"resolution":2.388657133974684932,"scale":9027.977410999999847},{"level":16,"resolution":1.19432856698734,"scale":4513.988705499999924},{"level":17,"resolution":0.597164283427525033,"scale":2256.994352499999877},{"level":18,"resolution":0.298582141779908494,"scale":1128.4971765},{"level":19,"resolution":0.149291070823808492,"scale":564.2485880000000407},{"level":20,"resolution":0.0746455354119041625,"scale":282.12429400000002},{"level":21,"resolution":0.0373227677059520813,"scale":141.06214700000001},{"level":22,"resolution":0.0186613838529760406,"scale":70.53107350000000508},{"level":23,"resolution":0.00933069192648802032,"scale":35.26553675000000254}]},"maxzoom":23,"resourceInfo":{"styleVersion":8,"tileCompression":"gzip","cacheInfo":{"storageInfo":{"packetSize":128,"storageFormat":"compactV2"}}},"currentVersion":10.7100000000000009,"capabilities":"TilesOnly,Tilemap","minLOD":0,"maxLOD":0,"exportTilesAllowed":false,"maxExportTilesCount":100000}`


**2nd response is:**

Request URL:
https://www.arcgis.com/sharing/rest/content/items/https://[I have the IP address here]/server/rest/services/Hosted/Acoustics_Survey2012/VectorTileServer?f=json
w/ response: 
`{"error":{"code":400,"messageCode":"CONT_0001","message":"Item does not exist or is inaccessible.","details":[]}}`

**Comment by jgravois** [comment]
i forgot, there is actually a cascade of _three_ requests.

things are most likely breaking down on this line.
https://github.com/Esri/esri-leaflet-vector/blob/8a9b6056b02d17cdfb22d0ffa5fba94e7ea7e45c/src/Layer.js#L39
i'd also guess that a relative url or two is what's giving us grief.

i don't work at Esri anymore and can't spare the time to investigate further and/or solve the problem on my own but i'm happy to lend a hand to anyone else willing to tackle it.

in the interest of making the problem easier to reproduce, a public service instance with a similar response signature would be a godsend.

**Comment by jwasilgeo** [comment]
@Mak-NOAA can you please give this a try again with the new v3 version of this library?

https://github.com/Esri/esri-leaflet-vector#lesrivectorvectortilelayer

**Comment by jwasilgeo** [comment]
@Mak-NOAA, we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet v3. I'll close this for now but feel free to reopen if something still isn't quite right.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
