### ISSUE TITLE
 when i enter a  import . L.esri it becomes undefined

### ISSUE THREAD

**Issue by CbastianRobles11** [Esri/esri-leaflet-vector#60]
Hi , I can help you , please
I have this import ( import {OpenStreetMapProvider} )from 'leaflet-geosearch' in my webpack app file. When it exits the Geocoding amount it stops working, when I comment the import it recognizes it.

how can i use this library and use reverse geocoding at the same time?

===================Below my code===========================
import { OpenStreetMapProvider} from 'leaflet-geosearch'

const lat=-0.22985;
const lng=-78.5249481;
let marker;

const map = L.map('mapa').setView([lat, lng], 13);

document.addEventListener('DOMContentLoaded',()=>{
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

      //para el buscador
      const buscador= document.querySelector('#formbuscador')
      buscador.addEventListener('input',buscarDireccion)

})

function buscarDireccion(e){
    //see esri
    console.log("Enfocate aqui=======================");
    
    console.log(L.esri);
    console.log("Enfocate aqui=======================");
    

    if(e.target.value.length>7){
        //si existe un pin anterior limpiarlo 
        

        //usar el geocode
         var geocodeService = L.esri.geocodeService();

        //utilizar el provider
        const provider = new OpenStreetMapProvider();
        console.log(provider);
        
        //la propiedad de buscar
        provider.search({query: e.target.value}).then((resultado)=>{
            //resultados
            console.log(resultado);
            //mostrar el mapa donde lo hayamos buscaod
            map.setView(resultado[0].bounds[0],15)  

            //mostrar el pin
            marker= new L.marker(resultado[0].bounds[0],{
                //para mover
                draggable:true,
                //mover el mapa con respecto al marcador
                autoPan:true

            })
            .addTo(map)
            .bindPopup(resultado[0].label)
            .openPopup()

         }

        )
    }
    
}

===========================================================

**Comment by gavinr** [comment]
Hi, please see the README files in https://github.com/Esri/esri-leaflet-geocoder and https://github.com/Esri/esri-leaflet-vector. Let us know if you more specific questions.
