### ISSUE TITLE
mapbox-gl-js v2.0.0  Breaking changes 

### ISSUE THREAD

**Issue by pluservice** [Esri/esri-leaflet-vector#61]
Starting from version 2.0 mapbox-gl-js is no longer open source , live examples that link to the latest version of mapbox-gl-js are not working anymore http://esri.github.io/esri-leaflet/examples/vector-basemap.html

We report about MapLibre GL,  a community led fork derived from mapbox-gl-js
https://github.com/maplibre/maplibre-gl-js

**Comment by jwasilgeo** [comment]
@pluservice thanks for the info, you're right about that. `esri-leaflet-vector` v3 uses `mapbox-gl-js` v1 internally and will continue to be a viable and recommended way to render vector tile basemaps and layers in Leaflet + esri-leaflet projects.

For those still looking for more info on the changes introduced earlier this year, we just refreshed the docs pages and changelogs to reflect what's new at esri-leaflet v3.

Live examples and API docs:

- https://esri.github.io/esri-leaflet

Related repo changelogs:

- https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-geocoder/blob/master/CHANGELOG.md
- https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md

And check out the ArcGIS for Developers pages focusing on esri-leaflet:

- https://developers.arcgis.com/esri-leaflet/
