### ISSUE TITLE
esri-leaflet-vector/examples/custom-vtl.html Not Working

### ISSUE THREAD

**Issue by parksconservancy** [Esri/esri-leaflet-vector#66]
Hi-
When testing the code referenced here : esri-leaflet-vector/examples/custom-vtl.html in both jsfiddle and VSCode I'm getting the following errors:

Failed to load resource: the server responded with a status of 404 (Not Found) - esri-leaflet-vector-debug.js:1
Uncaught TypeError: Cannot read property 'vectorTileLayer' of undefined - test.html:43 

Any thoughts on why this is happening would be really appreciated.

Cheers.

**Comment by jwasilgeo** [comment]
@parksconservancy those examples are intended for developer testing/debugging. The error is indicating that there’s an issue loading a file that is referenced _locally_ that won’t exist in jsfiddle:

> 404 (Not Found) - esri-leaflet-vector-debug.js

You can either try out the developer instructions in the README to try out the example files as-is, or more simply replace your script tags with what can be found in the main code snippet here:

https://github.com/Esri/esri-leaflet-vector#example

Hope that helps you get underway.

**Comment by zac-stanley** [comment]
Thanks @jwasilgeo  I'm cooking now.
