### ISSUE TITLE
Sources with layers without layout property cannot be added to a map (e.g. Esri World Contour Service)

### ISSUE THREAD

**Issue by jag-eagle-technology** [Esri/esri-leaflet-vector#71]
resolved by #70

**Comment by jwasilgeo** [comment]
Thank you for your help and contribution @jag-eagle-technology.

https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md#upcoming-changes

**Comment by jwasilgeo** [comment]
available on https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.0.1
