### ISSUE TITLE
Sources other than 'esri' not supported when loading from item id

### ISSUE THREAD

**Issue by jag-eagle-technology** [Esri/esri-leaflet-vector#72]
The code within the utils.js function loadStyleFromItem, line 59 looks for the source named 'esri', but does not look for any other services (unless error is true). The World Contours service, id 51ca3ce6a16d4080ad955dacd6dd2fe2, only has the source name 'contours', and thus cannot be added as a vector tile layer by id.

**Comment by jag-eagle-technology** [comment]
Yup, now that #71 is resolved

**Comment by gavinr** [comment]
This should be resolved in #91 - after the next release this should be fixed.

**Comment by jwasilgeo** [comment]
available on https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.0.1
