### ISSUE TITLE
Update peerDependency esri-leaflet ^2.3.0 to >2.3.0?

### ISSUE THREAD

**Issue by slutske22** [Esri/esri-leaflet-vector#82]
I've got [an issue](https://github.com/slutske22/react-esri-leaflet/issues/3) in my react wrapper for this plugin.  I think the issue is that for any project using this plugin with esri-leaflet v3, esri-leaflet-vector is expecting to find the peerDependency esri-leaflet ^2.3.0 in the parent project.  Now that esri-leaflet is up to v3, shouldn't we change the peerDependency of this package from `^2.3.0` to `>2.3.0` (the difference is subtle, but material - [npm smvr ranges](https://docs.npmjs.com/cli/v7/using-npm/semver#ranges)), so any version greater than 2.3.0, including ^3.x.x versions, will be able to be resolved?  Has anyone else run into this trying to use esri-leaflet 3 with this plugin?

**Comment by gavinr** [comment]
I have not noticed any issues myself. If possible, do you have replication steps that would show the issue?

**Comment by slutske22** [comment]
I created a blank folder, cd into that folder, and initialize an npm package with npm init -y. Then install `npm i leaflet esri-leaflet`. After that, I `npm i esri-leaflet-vector`. I get some peerDependency warnings:

<img width="1050" alt="Screen Shot 2021-05-10 at 12 50 55 PM" src="https://user-images.githubusercontent.com/52637023/117717309-81241f80-b18f-11eb-906b-6c0097aa4b53.png">

I guess its a minor issue, but making that change from `^` to `>` would get rid of that warning, which might be confusing considering this plugin works with esri-leaflet v3.

**Comment by gavinr** [comment]
We are running into a similar issue with `esri-leaflet-geocoder` here: https://github.com/Esri/esri-leaflet-geocoder/issues/272

I plan to change the `peerDependencies` to `"esri-leaflet": ">2.3.0",` like you advise, but similar to the esri-leaflet-geocoder we will also update the dependencies version of `"esri-leaflet": "^3.0.0",`

**Comment by slutske22** [comment]
Well it depends.  Do you expect your users to install it themselves?  Or do you want it to be automatic - i.e., if you install esri-leaflet-geocoder, you get esri-leaflet automatically installed?  My inclination would be to keep it under peerDependencies, considering this is a plugin for esri-leaflet, which itself is a plugin for leaflet.  IMO, people using this (or geocoder) plugin should take ownership of their leaflet and esri-leaflet installations on their own *first* - so it should be a peerDep.  That's just my humble 2 cents on the matter.

That being said, from what I understand, [npm 7 now automatically installs all peerDependencies](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies), so this may be a moot point for npm 7 users.
