### ISSUE TITLE
Vector tiles are showing in the wrong place and in the wrong scale

### ISSUE THREAD

**Issue by javalonde** [Esri/esri-leaflet-vector#86]
Hi Everyone!

Where should I start looking for an error if after adding a layer 

`L.esri.Vector.vectorTileLayer("https://MY_ARCGIS/rest/services/Norway/VectorTileServer").addTo(map);`

I'm using esri-leaflet@3.0.0 and leaflet 1.7.1

it is shown in the wrong place and in the wrong scale?

![image](https://user-images.githubusercontent.com/44463908/118135295-23980900-b403-11eb-871e-b95762f78e5a.png)

Thanks a lot for any help!

Regards
Mik

**Comment by jwasilgeo** [comment]
@javalonde can you please share with us a public, live demo of this problem? (codepen, jsbin, code sandbox, etc.)

**Comment by javalonde** [comment]
Yes, tiles should be shown on Norway:

https://codepen.io/javalonde/pen/mdWPeoQ

**Comment by jwasilgeo** [comment]
It appears that your layer is in a spatial reference with a `wkid` of 25833, which I sense is the cause of the behavior.

https://services.geodataonline.no/arcgis/rest/services/GeocacheVector/GeocacheBasis/VectorTileServer?f=pjson

I've not tried this myself before with a VectorTileLayer, but can you look into using something like <https://github.com/kartena/Proj4Leaflet>?

We have a couple of `esri-leaflet` samples using other layer types and non-Web Mercator Leaflet maps here:

- https://esri.github.io/esri-leaflet/examples/non-mercator-projection.html
- https://esri.github.io/esri-leaflet/examples/non-mercator-projection-2.html

Alternatively, can your VectorTileServer be reprojected and republished in Web Mercator?

**Comment by javalonde** [comment]
Thanks, I suspected a different projection might be the cause, but didn't know where to check it.

I added a proper csr to the map but unfortunately it doesn't work properly. Maybe array resolutions is not correct (found via google). Can you take a look ?

https://codepen.io/javalonde/pen/mdWPeoQ

I suppose it might be hard to sort it out like this, but I hope it's possible. I will also look at the possibilities of what you proposed for reproject  and republish it in Web Mercator.

**Comment by javalonde** [comment]
..and one more new example where it was used VectorTileServer
with:
{"wkid":102100,"latestWkid":3857}

https://codepen.io/javalonde/pen/bGqpLyM

**Comment by jwasilgeo** [comment]
Bardzo interesujące...

I can sometimes find Norway in either of your LeafletJS codepens when I zoom out (thanks again for making those), but it is never in the right spot, regardless of the projection.

And yet, when I use either of your VectorTileServers in the ArcGIS API for Javascript ([live demo here](https://developers.arcgis.com/javascript/latest/sample-code/layers-vectortilelayer/)) they seem to work as we would expect.

We'll need to spend more time thinking about this one.

**Comment by Getiem** [comment]
I have the same problem with 28992 projection vector tiles. Even if i set all resolutions correct (copy the full array of values from the rest service json).

**Comment by javalonde** [comment]
I experimented by adding `crs: 'EPSG: 4326'`
but with no positive effect. 
![image](https://user-images.githubusercontent.com/44463908/119325850-9ca82380-bc81-11eb-98d5-ce7ae19596c4.png)

**Comment by javalonde** [comment]
Hi, I mentioned the problem on the stackoverflow and got this answer, can this help?

https://stackoverflow.com/questions/67704695/vector-tiles-are-showing-in-the-wrong-place-and-in-the-wrong-scale-in-esri-leafl

I tried to overwrite `metadata.tileInfo.lods`
by values from

https://vectortileservices3.arcgis.com/GVgbJbqm8hXASVYi/arcgis/rest/services/Santa_Monica_Mountains_Parcels_VTL/VectorTileServer?f=pjson

in the` formatStyle (style, styleUrl, metadata, token)`

but with no positive effect also.

**Comment by Getiem** [comment]
Did you try creating a CRS object with your vectortile service CRS?  

I tried it with my own CRS (28992), but ran into the problem of the ArcGIS Enterprise connection (see other issue). Did not yet try this with a 28992 service at arcgis online. Maybe you can be succesfull with it:

Sample CRS i tried with:  
`var RD = new L.Proj.CRS( 'EPSG:28992','+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +towgs84=565.2369,50.0087,465.658,-0.406857330322398,0.350732676542563,-1.8703473836068,4.0812 +no_defs', {
          resolutions: [1625.6032512065026, 812.8016256032513, 406.40081280162565, 203.20040640081282, 101.60020320040641, 50.800101600203206, 25.400050800101603, 12.700025400050801, 6.350012700025401, 3.1750063500127004, 1.5875031750063502, 0.7937515875031751, 0.39687579375158755, 0.19843789687579377, 0.09921894843789689, 0.04960947421894844, 0.02480473710947422, 0.01240236855473711, 0.006201184277368555, 0.0031005921386842777],
          //bounds: L.bounds([108494, 476855], [116172, 486953]),
          bounds: L.bounds([-285401.92, 22598.08], [595401.9199999999, 903401.9199999999]),
          origin: [-285401.92, 903401.92]
        }
      );
`
Change resolutions to the ones mentioned on your own CRS REST service, and the change also bounds and origin.


Do not forget to add proj leaflet in your source references:
` 
  <script src="https://unpkg.com/proj4@2.4.3"></script>
  <script src="https://unpkg.com/proj4leaflet@1.0.1"></script>`


Offcoarse, after defining this one, use this CRS then as the one in the optionslist of your map object.

**Comment by jwasilgeo** [comment]
Cześć @javalonde, I double-checked and it turns out this can only support the Web Mercator projection, since itself it [relies directly upon `mapbox-gl-js v1`](https://github.com/Esri/esri-leaflet-vector#dependencies).

https://docs.mapbox.com/help/glossary/projection/

That would also help explain why we saw it work with your Norway projection in the ArcGIS API for JavaScript but not with `LeafletJS`  + `esri-leaflet` + `esri-leaflet-vector` + `Proj4Leaflet`. **We'll make sure to document this soon.**

But, the comment at the end of this `mapbox-gl-js` issue hints at this constraint potentially changing sometime in the near future:
https://github.com/mapbox/mapbox-gl-js/issues/3184. It may be interesting to follow the progress of that effort to see what might change over time.

**Comment by javalonde** [comment]
Dziękuję ! Thanks for help.

**Comment by jwasilgeo** [comment]
The documentation for this is available now in the recent [v3.1.0 release](https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.1.0). 🎉

**Comment by axelio** [comment]
cześć @jwasilgeo 

Since https://github.com/mapbox/mapbox-gl-js/issues/3184 is done now, do you know how can one use vector maps in non-mercator projection?
This the same scenario as @jwasilgeo had - Norwegian ArcGIS maps. Problem appears on close zoom & map panning, seems something with the styling does not work correctly.

Find below the code sample based on starting example and https://esri.github.io/esri-leaflet/examples/non-mercator-projection.html

https://codepen.io/axelito/pen/QWQZBEg
