### ISSUE TITLE
Document web mercator requirement

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-vector#94]
As mentioned, we should document this: https://github.com/Esri/esri-leaflet-vector/issues/86#issuecomment-852408185

Also, since it's [tripping other up](https://github.com/Esri/esri-leaflet-vector/issues/93#issuecomment-860883132), we should add a `console.error()` (or `console.warn()`?) message to show when not using web mercator

**Comment by jwasilgeo** [comment]
@gavinr @patrickarlt to catch this one and put in a warning for `L.esri.Vector.vectorTileLayer` [right about at this spot](https://github.com/Esri/esri-leaflet-vector/blob/master/src/VectorTileLayer.js#L59), which of these `spatialReference.wkid` properties do we want to rely upon? 

- `service.initialExtent.spatialReference.wkid`
- `service.fullExtent.spatialReference.wkid`
- `service.tileInfo.spatialReference.wkid`

Ref: <https://developers.arcgis.com/rest/services-reference/enterprise/vector-tile-service.htm>

**Comment by gavinr** [comment]
My vote would be `service.tileInfo.spatialReference.wkid`

**Comment by jwasilgeo** [comment]
This is available now in the recent [v3.1.0 release](https://github.com/Esri/esri-leaflet-vector/releases/tag/v3.1.0). 🎉

**Comment by scaddenp** [comment]
There are a lot vector tile layers in another projection that have been published on arconline that I would like to use. Is it a lost cause to be able to use them in leaflet or is it a programming issue that just needs somebody to work on it?

**Comment by jwasilgeo** [comment]
@scaddenp a good explanation for this limitation is described here: https://github.com/Esri/esri-leaflet-vector/issues/86#issuecomment-852408185

For now we have to wait and hope for `mapbox-gl-js v1` (or `maplibre-gl-js`) to add this functionality.

**Comment by scaddenp** [comment]
Hmm, this is complicated by the whole "make mapbox work in non-mercator tiles" which is a larger problem than rendering a non-mercator VectorTileService. I think I need a deep dive into code at some point. Support for the ESRI tiling schemes already exists in the leaflet code - in image tile services. A native renderer for pbf looks to be the crux.
